version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - web

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 8080:80
    volumes:
      - /app/node_modules
      - ./frontend/web:/app
    env_file:
      - ./frontend/.env
    networks:
      - web
  #
  #  postgres:
  #    image: postgres:9.6-alphine
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - /data/postgres:/data/postgres
  #    env_file:
  #      - ./backend/.env
  #    networks:
  #      - postgres

  #  pgadmin:
  #    links:
  #      - postgres:postgres
  #    image: dpage/pgadmin4
  #    ports:
  #      - "8080:80"
  #    volumes:
  #      - /data/pgadmin:/root/.pgadmin
  #    env_file:
  #      - ./backend/.env
  #    networks:
  #      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.name=elasticsearch
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/var/lib/elasticsearch
    ports:
      - 9200:9200
    networks:
      - elastic

#  elastic search with multiple nodes
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
#    container_name: es01
#    environment:
#      - node.name=es01
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - elastic
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
#    container_name: es02
#    environment:
#      - node.name=es02
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data02:/usr/share/elasticsearch/data
#    networks:
#      - elastic
#  es03:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
#    container_name: es03
#    environment:
#      - node.name=es03
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es02
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data03:/usr/share/elasticsearch/data
#    networks:
#      - elastic

volumes:
  data01:
    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local

networks:
  web:
    driver: bridge
  postgres:
    driver: bridge
  elastic:
    driver: bridge
